package ggTCalculator;


/**
* ggTCalculator/ProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 18:26 Uhr UTC
*/

public interface ProcessOperations 
{
  boolean terminate ();
  void set_params (ggTCalculator.Process left, ggTCalculator.Process right, int number, ggTCalculator.Log log, double delay, int timeout);
  void message (int number);
  void stop ();
} // interface ProcessOperations
