package ggTCalculator;


/**
* ggTCalculator/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vsp2.idl
* Donnerstag, 2. Juni 2011 14:27 Uhr UTC
*/

public interface StarterOperations 
{
  void createProcess (int count);
  void quitProcess ();
  void quit ();
} // interface StarterOperations
