package ggTCalculator;


/**
* ggTCalculator/StarterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 17:35 Uhr UTC
*/

abstract public class StarterHelper
{
  private static String  _id = "IDL:ggTCalculator/Starter:1.0";

  public static void insert (org.omg.CORBA.Any a, ggTCalculator.Starter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ggTCalculator.Starter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ggTCalculator.StarterHelper.id (), "Starter");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ggTCalculator.Starter read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StarterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ggTCalculator.Starter value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ggTCalculator.Starter narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ggTCalculator.Starter)
      return (ggTCalculator.Starter)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ggTCalculator._StarterStub stub = new ggTCalculator._StarterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ggTCalculator.Starter unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ggTCalculator.Starter)
      return (ggTCalculator.Starter)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ggTCalculator._StarterStub stub = new ggTCalculator._StarterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
