package ggTCalculator.CoordinatorPackage;

/**
* ggTCalculator/CoordinatorPackage/alreadyRunningHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 22:33 Uhr UTC
*/

public final class alreadyRunningHolder implements org.omg.CORBA.portable.Streamable
{
  public ggTCalculator.CoordinatorPackage.alreadyRunning value = null;

  public alreadyRunningHolder ()
  {
  }

  public alreadyRunningHolder (ggTCalculator.CoordinatorPackage.alreadyRunning initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggTCalculator.CoordinatorPackage.alreadyRunningHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggTCalculator.CoordinatorPackage.alreadyRunningHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggTCalculator.CoordinatorPackage.alreadyRunningHelper.type ();
  }

}
