package ggTCalculator;


/**
* ggTCalculator/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 22:33 Uhr UTC
*/

public interface CoordinatorOperations 
{
  void addStarter (String startername, ggTCalculator.Starter starter);
  void addProcess (String startername, int id, ggTCalculator.Process process);
  String[] getStarterList ();
  int calculate (int timeout, int mindelay, int maxdelay, int minprocess, int maxprocess, int ggT, ggTCalculator.Log log) throws ggTCalculator.CoordinatorPackage.noStarter, ggTCalculator.CoordinatorPackage.alreadyRunning;
  void finished (int r);
  boolean terminationStart ();
  boolean terminationStop ();
  void quit ();
} // interface CoordinatorOperations
