package ggTCalculator;

/**
* ggTCalculator/CoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 18:26 Uhr UTC
*/

public final class CoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public ggTCalculator.Coordinator value = null;

  public CoordinatorHolder ()
  {
  }

  public CoordinatorHolder (ggTCalculator.Coordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggTCalculator.CoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggTCalculator.CoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggTCalculator.CoordinatorHelper.type ();
  }

}
