package ggTCalculator;

/**
* ggTCalculator/LogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 17:35 Uhr UTC
*/

public final class LogHolder implements org.omg.CORBA.portable.Streamable
{
  public ggTCalculator.Log value = null;

  public LogHolder ()
  {
  }

  public LogHolder (ggTCalculator.Log initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggTCalculator.LogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggTCalculator.LogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggTCalculator.LogHelper.type ();
  }

}
