package ggTCalculator;


/**
* ggTCalculator/LogOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 18:26 Uhr UTC
*/

public interface LogOperations 
{
  void log (String user, String msg);
} // interface LogOperations
