package ggTCalculator;


/**
* ggTCalculator/Process.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 18:26 Uhr UTC
*/

public interface Process extends ProcessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Process
