package ggTCalculator;


/**
* ggTCalculator/Coordinator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vsp2.idl
* Donnerstag, 2. Juni 2011 14:27 Uhr UTC
*/

public interface Coordinator extends CoordinatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coordinator
