package ggTCalculator;

/**
* ggTCalculator/ProcessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vsp2.idl
* Donnerstag, 2. Juni 2011 14:27 Uhr UTC
*/

public final class ProcessHolder implements org.omg.CORBA.portable.Streamable
{
  public ggTCalculator.Process value = null;

  public ProcessHolder ()
  {
  }

  public ProcessHolder (ggTCalculator.Process initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggTCalculator.ProcessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggTCalculator.ProcessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggTCalculator.ProcessHelper.type ();
  }

}
