package ggTCalculator;


/**
* ggTCalculator/ProcessPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 20:35 Uhr UTC
*/

public abstract class ProcessPOA extends org.omg.PortableServer.Servant
 implements ggTCalculator.ProcessOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("terminate", new java.lang.Integer (0));
    _methods.put ("set_params", new java.lang.Integer (1));
    _methods.put ("message", new java.lang.Integer (2));
    _methods.put ("stop", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ggTCalculator/Process/terminate
       {
         boolean $result = false;
         $result = this.terminate ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ggTCalculator/Process/set_params
       {
         ggTCalculator.Process left = ggTCalculator.ProcessHelper.read (in);
         ggTCalculator.Process right = ggTCalculator.ProcessHelper.read (in);
         int number = in.read_long ();
         ggTCalculator.Log log = ggTCalculator.LogHelper.read (in);
         double delay = in.read_double ();
         int timeout = in.read_long ();
         this.set_params (left, right, number, log, delay, timeout);
         out = $rh.createReply();
         break;
       }

       case 2:  // ggTCalculator/Process/message
       {
         int number = in.read_long ();
         this.message (number);
         out = $rh.createReply();
         break;
       }

       case 3:  // ggTCalculator/Process/stop
       {
         this.stop ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ggTCalculator/Process:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Process _this() 
  {
    return ProcessHelper.narrow(
    super._this_object());
  }

  public Process _this(org.omg.CORBA.ORB orb) 
  {
    return ProcessHelper.narrow(
    super._this_object(orb));
  }


} // class ProcessPOA
