package ggTCalculator;


/**
* ggTCalculator/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ggTCalculator.idl
* Donnerstag, 2. Juni 2011 22:33 Uhr UTC
*/

public interface StarterOperations 
{
  String getName ();
  void createProcess (int count);
  void quitProcess ();
  void quit ();
} // interface StarterOperations
